### ISSUE TITLE
Reactions stuck in dark mode

### ISSUE THREAD

**Issue by fflaten** [bravo-kernel/bravo-kernel.com#170]
![image](https://user-images.githubusercontent.com/3436158/227782658-8c998ea9-dc96-45fe-b080-219e95248f93.png)

**Comment by fflaten** [comment]
Latest MS Edge. Cool, hadn't heard of Pliny before :)
It gets updated with light theme, but looks like a CSP issue.
![image](https://user-images.githubusercontent.com/3436158/227784388-12ae336d-b512-4684-9fa5-87cecfb4cb44.png)
![image](https://user-images.githubusercontent.com/3436158/227784348-0d3ab801-a220-4aea-bc6e-e5d692b3aa15.png)

**Comment by bravo-kernel** [comment]
Not sure what that means but I remember this line required some tweaking to get things up and running.

https://github.com/bravo-kernel/bravo-kernel.com/blob/main/next.config.js#L8

**Comment by bravo-kernel** [comment]
Also, Pliny is relatively new and far from perfect but at least it is a start. No css maintenance is the goal 🙏.
